Metrics/AbcSize:
  Max: 30
Metrics/LineLength:
  Max: 150
Metrics/MethodLength:
  Max: 30
Metrics/BlockLength:
  Max: 316
Style/Documentation:
  Enabled: false
Style/SignalException:
  Enabled: false
Style/SpaceInsideBrackets:
  Enabled: false
