language: ruby
cache: bundler
sudo: false
rvm:
- 2.0.0
- 2.1
- 2.2
branches:
  only:
  - master
notifications:
  slack:
    on_success: change
    on_failure: always
    rooms:
      secure: nsXeCpKObwW8JK5NzakOw/yTpirhF5jUOFOtKj0SVwJRv9iid/b6e8BTs6TQan8HjEtbVFGUXhNna8Q6xIzMsv9b6X1EUpC/djnY8HzvMqu3P9bTQKkRMvD4NIcIWRZybeG+zVXQSs8ExN8VS+8lw48p8fhvQaRCyn+Nwcdd+s1Hys7ow+XIKODl+g057SmPWhoAcBEEgHJurx/tUddjIuRLwXh3AKzJHWLbaib9+iQXhey48XhdYzp9YROxvFRFm//FpKtBXZrAmExqIJgyu1MtU6LWqflFjgZh1GRob9D8iS5K5AvunTCT35q9dSVS1EZHUvoQjeVxiYmbrM2i3tQyF3M+B+KKeiVNGIGnZB7miE7mUV3rl2Qfq8YOgSjvxDOxzu8uOms0bykWO+UKZDBzTATDEppmbXEekqfJnb86s+js+f1h8++lK7o8wq9aENbn51WjZm3iNFNPe5Ei2hcOnA4GQ7iVsOP1r3PBc6grpZQwDTaVfL4wGxXQ54TGlY8AMb50KFrZB/HrBpJjZTM39JDQb41uhgMxpT/8u11oK9bOwW2T1rfYiqxd6LiRCBjyKun4ublFZHINe83rKDLASbBq4LiL9C+s1i4Oke3RfuV3qSkt+HkNhLZaLRUiuUc0ZCBelqZh+Lkymp9L4NlC1PMBGUp9Xhqxw4R7o4s=
